module.exports.pipeline = require('pumpify')
module.exports.pipe = require('pump')
module.exports.duplex = require('duplexify')
module.exports.through = require('through2')
module.exports.concat = require('concat-stream')